POST http://localhost:5000/user/register
Content-Type: application/json

{
    "firstName": "said",
    "lastName": "Kherif",
    "email": "said.kherif@gmail.com",
    "username": "saidal",
    "password": "S6m8h5B3lAxjJI"
}
###
POST http://localhost:5000/user/login
Content-Type: application/json

{
    "username": "saidal",
    "password": "S6m8h5B3lxjJI"
}